# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d36fee837c1cf3bae79dc0f715e79d42ecac431224919cd57f5e20d3f593193ab050f187fe38e8a248381e0b1bf13a35601458069c4a0fe35d8847fce36c100b

test:
  secret_key_base: d41ee185ed43486ff920e337022706ec2dd9dbd03f9686dcf69763f3e3e16a45bd05905750bdbfda57ebee1f18fb39a378f7897b8c48b96a0ba4de6d2d1cc7dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
